### ISSUE TITLE
Refine automatic Exports

### ISSUE THREAD

**Issue by ModischFabrications** [ModischFabrications/turn_indicator_pcb#1]
No idea how it works yet, but it would be nice to use it. Look into https://github.com/nerdyscout/kicad-exports/issues/27 for some hints. 

https://github.com/nerdyscout/kicad-exports/blob/main/config/bundle/fabrication.jlcpcb.kibot.lst

**Comment by ModischFabrications** [comment]
1. Check rough file existence
2. Check DRC, ERC, ...
3. build pretty images
4. build gerber export for pcb manufacturing

**Comment by ModischFabrications** [comment]
Filter out trash that is unused, see https://github.com/nerdyscout/kicad-exports/issues/30

**Comment by ModischFabrications** [comment]
Linking image files into the readme would be the gold standard, see if that's possible. 

Oh, create badges as well while at it.

**Comment by ModischFabrications** [comment]
Retention is limited to 90 days, which would render image links dead after a while. Too bad...

https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#artifact-and-log-retention-policy

**Comment by nerdyscout** [comment]
> Linking image files into the readme would be the gold standard, see if that's possible.
> Retention is limited to 90 days, which would render image links dead after a while. Too bad...

unfortunately yes... that is why I, eg for schematics, create svg files and push those into a separate branch of the repository.
